### ISSUE TITLE
GA4 - product payload

### ISSUE THREAD

**Issue by niteshsharoff** [stape-io/impact-tag#1]
_Thanks for this tag btw, very helpful!_

Just sharing a couple of tweaks that may be helpful for GA4 payloads that might be useful to build in:
- Currently the code is prepared for the UA EE product payload, GA4 uses `item_id` , `item_sku` and `item_category` which aren't being picked up (`sku`/`id`/` category` are but `item_sku`/`item_id`/`item_category` aren't)
- (Optional) `coupon` can be present on each item level or order level which could be leveraged (Optional because this can be done with already build additional params functionality within the tag)
- (Optional)  `currency` could also be taken from GA4 item payload (or event data) (Optional because this can be done with already built additional params too)

**Comment by Bukashk0zzz** [comment]
Hi,

Thanks for such a detailed issue description.
I already added to my to-do list made fixes for issues you found.

**Comment by Bukashk0zzz** [comment]
Done. https://github.com/stape-io/impact-tag/commit/c3ad666c45b678d1184d0e1cae5c57043f345f8e
